version: '3.8'
services:
  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    volumes:
      - ./src:/src
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - api-service
    entrypoint:
      - "uvicorn"
      - "main:app"
      - "--host"
      - ${APP_HOST}
      - "--port"
      - ${APP_PORT}
      - "--reload"
networks:
  api-service:
    driver: 'bridge'