version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: .docker/webapi.Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
      - 5678:5678