version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: .docker/webapi.Dockerfile
    image: fastapi:dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8080
